### ISSUE TITLE
[Question] Help with installation (Windows 10, Anaconda)

### ISSUE THREAD

**Issue by agamemnonc** [dashesy/CereLink#107]
I have a conda environment with PyQt5 installed. 
Installation via setup.py is currently failing  with
`RuntimeError: Cannot find Qt in registry nor QTDIR is set`.

Is installation of the full Qt framework (~40 GB) required for the library to work? I am only planning to use the Python wrapper.

Thanks.

**Comment by cboulay** [comment]
The Qt Installer gives you the option to choose which components to install. You only need to install one set of C++ libs, so this should be much smaller than 40 GB.

Anyway, it should be possible to use the Qt libs that come with conda, though I haven't tried this myself. It would be nice if something like `set QTDIR=%CONDA_PREFIX%\Library\bin` worked. However, this won't work because of some of the assumptions our setup.py makes about the Qt folder structure. I think you can probably copy the contents of this folder (at least all the files that start with 'Q' or 'q') to somewhere like `D:\Qt5.x\lib` then use `set QTDIR=D:\Qt5.x`

I could modify setup.py to find conda and its Qt, but I think my time would be better spent setting up a CI system that builds and deploys to pypi so you can just do a `pip install cerebus` and not even have to build CereLink or have Qt at all. Finding that time is hard.

If this solves your problem then please close the issue.
-Chad

**Comment by agamemnonc** [comment]
Thank you very much for your help.

I have done that but now compilation fails with the following message:

> running install
running bdist_egg
running egg_info
writing cerebus.egg-info\PKG-INFO
writing dependency_links to cerebus.egg-info\dependency_links.txt
writing requirements to cerebus.egg-info\requires.txt
writing top-level names to cerebus.egg-info\top_level.txt
reading manifest file 'cerebus.egg-info\SOURCES.txt'
writing manifest file 'cerebus.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
skipping 'cerebus\cbpy.cpp' Cython extension (up-to-date)
building 'cerebus.cbpy' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\nak142\Miniconda3\envs\myo\lib\site-packages\numpy\core\include -IC:\Users\nak142\Coding\cerelink\dist\include -IC:\Users\nak142\Coding\cerelink\compat -ID:\Qt5.9\include -IC:\Users\nak142\Miniconda3\envs\myo\include -IC:\Users\nak142\Miniconda3\envs\myo\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\cppwinrt" /EHsc /Tpcerebus\cbpy.cpp /Fobuild\temp.win-amd64-3.7\Release\cerebus\cbpy.obj
cbpy.cpp
cerebus\cbpy.cpp(614): fatal error C1083: Cannot open include file: 'cbhwlib.h': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.14.26428\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Not sure why `cbhwlib.h` cannot be found as I can see it in the directory. Any ideas? Please excuse my ignorance!

**Comment by cboulay** [comment]
You have to build the cbsdk library first (and that requires Qt). Sorry if that wasn't clear from the build instructions.

Read from [here](https://github.com/dashesy/CereLink/blob/master/BUILD.md#using-the-cmake-build-system-supported).

**Comment by cboulay** [comment]
BTW, I'm sorry I'm only now realizing that you probably didn't see [the release page](https://github.com/dashesy/CereLink/releases).

You can just download the .whl file from there and then `pip install wheel.whl` (where wheel.whl is the full name of the file you downloaded). As long as it's compatible with your platform and version of Python then you shouldn't have to do anything else.

**Comment by agamemnonc** [comment]
Wow, how did I miss that?

Thanks a lot!
