### ISSUE TITLE
Update outdated hwlib to support newest firmware and central (hwlib 3.10)

### ISSUE THREAD

**Issue by FlorianFranzen** [dashesy/CereLink#45]
Is there a reason why this repository does not contain the newest chhwlib.h (v3.10) that comes with the Cerebus Windows Suite?

These changes seem to be missing, some even signed of by @dashesy and @jsoutherland:

```
// 3.10 - 23 Oct 2014 hls - Added reboot capability for extension loader
//        26 Jul 2014 js  - Added analog output to extension
//        18 Mar 2014 sa  - Add triggered digital output
//         3 Mar 2013 eaz - Adjust MTU
```

Or is this not the official development repo of the cbsdk?

**Comment by dashesy** [comment]
@FloFra as soon as I get the latest `cbhwlib` from Hyrum I can merge and update to the latest, you as a customer can ask Blackrock for the file, or even direct contribution :)

**Comment by FloFra** [comment]
Sorry, I am somewhat confused. So far I have only received the precompiled Windows version of the Cerebus SDK Library and I was rather surprised to also find the source code licensed under GPL on github.

Since it is released under GPL I assumed there must be an official public repository but based on your comment this repo is apparently not it. Sorry for the confusion.

I will talk to Blackrock about this and see what come out of it.

**Comment by dashesy** [comment]
@FloFra This is GPLv2 public release that Blackrock holds the copyright, I do not work for Blackrock. Blackrock sends me the latest protocol header file (`cbhwlib`) and I merge it, usually that would be the only change needed. I will email Hyrum to get the latest.

**Comment by FloFra** [comment]
With the hwlib of CereLink at v3.9 accessing any of the channel info on a v3.10 instrument will return incorrect results (most often it complains that the channel number is invalid, because chid is zero). This is due to the fact that v3.10 uses larger cbPKT_CHANINFO packages and buffers resulting in data being misinterpreted.

I am in contact with Blackrock to properly resolve this issue and I will sent a pull request as soon as the supply me with the new version.

To avoid any issues in the future, I also submitted #50 (and #49).

**Comment by dashesy** [comment]
Yes, new version requires newer `cbhwlib.h` and `cbhwlib.cpp`. I will tag the current version as 6.04 then should merge the new protocol. The protocols ABI is not backward compatible.

**Comment by FloFra** [comment]
If that has always been the case, then I don't understand why nobody ever thought to check the hwlib version in the code on connection.

This SDK has been outdated for almost a year now with no note or warning anywhere. 

If you want I can at least post a patch that makes the current code compatible with 3.10 (without adding any of the new functionality but preserving old functionality).

**Comment by dashesy** [comment]
Yes, unless one installs the compatible version with the library, many people do not update that often. The way I have done it from 6.03 to 6.04 was to tag it as `v6.03` and then merge 6.04. 
If someone wants an older version (but with fixes) there is always an option to backport and call it `v6.03.02`. Unfortunately there is no easy option. I always hoped Blackrock would step up and at least do some protocol updates more often.

**Comment by FloFra** [comment]
Just in case you have already updated, you can just apply the following simple patch to get the current version of CereLink to work with 3.10 hardware: FloFra@a47610c

**Comment by dashesy** [comment]
This will only change the version, they could have different protocols that may result in unknown or unexpected results

**Comment by FloFra** [comment]
No, this patch indeed contains all the changes that are necessary to make the binary protocol compatible again. 

Since I do not have access to the source code of the latest version, but was only able to extract these protocol changes from the latest hwlib headers, It does of course not contain any of the new functionality.

**Comment by cboulay** [comment]
FYI, Nick Halper at Blackrock informed me that he recently shared the source for 3.10 with @dashesy .

**Comment by dashesy** [comment]
The newer version is now merged
