### ISSUE TITLE
MSVC CE, linking cbsdk.dll, #include "cbhwlib.h" requires NO_AFX to be defined.

### ISSUE THREAD

**Issue by cboulay** [dashesy/CereLink#63]
I wrote an application that links to cbsdk and uses some of the types declared in cbhwlib.h. In MacOS it worked fine. In Windows it failed because it could not find some types used in function arguments defined in cbhwlib.h. This is because these types are only defined for non-Windows ([here](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.h#L164-L191)) or via `#include <windows.h>` if NO_AFX is defined ([here](https://github.com/dashesy/CereLink/blob/master/cbhwlib/cbhwlib.h#L59-L62)).

I will create a stub in the Wiki for "How to use cbsdk" and put in this little bit of information for now, but I think a better solution is needed.

* The STL has replacements for all the offending ALLCAPS types (e.g., UINT16 -> uint16_t).
* In the provided .sln files, NO_AFX is defined by default, and it was defined in the CMakeLists.txt too (I wonder why @FlorianFranzen removed this in his fork?). Maybe <windows.h> should be included by default in Windows builds and not require a compiler definition.
* As much as possible, it would be good to decouple cbsdk.h from cbhwlib.h so cbhwlib.h is no longer required.
    * `cbSdkCCFEvent` needs `cbStateCCF` from cbhwlib.h. This is just an enum and can be moved easily.
    * `cbSdkCCF` needs `cbCCF`. This is a complicated dependency to work around and any attempt to do so would need your guidance.

**Comment by dashesy** [comment]
Yes `NO_AFX` should be defined, to avoid bringing in some MFC stuff, from what I remember. This is because Blackrock's code uses same headers and it is using MFC.
Those CCF structs would be difficult to wrap, because they are something like filed generated by protocol buffer with lots of fields. Can #ifdef them out for now, I am not sure if anyone uses that XML file (I wish I had not added XML, anything else is better!).

**Comment by cboulay** [comment]
Closed with #66
