### ISSUE TITLE
build cerelink7.0 on ubuntu failed

### ISSUE THREAD

**Issue by DingkunLiu** [dashesy/CereLink#83]
I tried to build branch cerelink7.0 but failed with the error pstdint.h not found. 
I checked the cmakelist and found the parameter "lib_incl_dirs" seems not consider Linux platform. Does it have anything to do with the error?

**Comment by cboulay** [comment]
Sorry I need more info about the error than that. In general, a single line of the error is usually not enough to help me debug so your safest bet is to just post the entire block of text.

I think I know what the problem is, but I need to know which file or files are producing that error on your system.

Also, what version of gcc are you using, and what was the cmake command you used?

**Comment by cboulay** [comment]
Actually, in this case, I don't need all that info. The problem was as easy as you thought. I'll post here when it's fixed and pushed.

**Comment by DingkunLiu** [comment]
Fine! Thank you so much. I will wait for your new push.

**Comment by cboulay** [comment]
OK I just pushed something that works on my ubuntu system, but I don't like it. I have another idea to fix it that I prefer. It shouldn't take me long but you can use what I just pushed in the meantime.

If you plan on installing the python package, then pay attention to [these lines](https://github.com/dashesy/CereLink/blob/CereLink7.0/setup.py#L108-L113). Chances are you are going to have to modify the contents of `/usr/lib/x86_64-linux-gnu/qt-default/qtchooser/default.conf`. In my case all I had to do was change the `qt4` on the first line to `qt5`.

**Comment by cboulay** [comment]
Turned out to be pretty easy. The preferred fix is now up. The comment about changing your default qt5 still stands.
