### ISSUE TITLE
Get trial event and continuous data simultaneously 

### ISSUE THREAD

**Issue by DingkunLiu** [dashesy/CereLink#84]
In cerelink there seems no way I can get trial event and trial continuous data at the same time. 
I have to call two functions which I notice both call cbSdkGetTrialData in cbsdk but with different parameters. 
If I call the two functions sequentially, can simultaneity still be guaranteed? Is there need to implement a function just like cbmex function onTrialData?

**Comment by cboulay** [comment]
For the sake of clarity, let's say "CereLink" is the name of the project, "cbsdk" is the name of the C++ SDK, "cbpy" is the name of the Python wrapper around cbsdk, and "cbmex" is the Matlab wrapper around cbsdk. Using those terms, can you please clarify what you're trying to do?

If you're using cbsdk, then you can call cbSdkGetTrialData just like how it's done in cbmex.

Just as an aside, whether you get the data with one or two calls to cbSdkGetTrialData, please use the timestamps to align your data.

**Comment by DingkunLiu** [comment]
Sorry I mean "cbpy". In "cbpy" there are two functions called "trial_event" and "trial_continuous". My worry is that if I call the two functions at different time, event data and continuous data may be incompatible due to new arrival streaming data. 
Another question, the data seems come from  same buffer. So if I need to get trial event and data I should only reset the buffer once when I call "trial_event" and "trial_continuous" sequentially, is that true?

**Comment by cboulay** [comment]
I see what you mean. Hmm... I guess I haven't come across this problem because I run my continuous-data-fetcher and my event-data-fetcher in separate processes, so they run entirely independently of each other. 

It's probably worthwhile to add a function to cbpy to fetch both continuous and event data in one call. Do you think you can do that and make a pull request? I probably won't have time to get to that for a few weeks at best.

**Comment by DingkunLiu** [comment]
OK I will give it a try next week.
