### ISSUE TITLE
msvc: Incorrect CMake configuration for static lib when used to build Python lib

### ISSUE THREAD

**Issue by stinos** [dashesy/CereLink#96]
The static library project (cbsdk_static.vcxproj) is configured to use the Multi-threaded Dll runtime (/MD switch) however it seems the Python library wants the static version instead (/MT switch), relevant part of output of `pip install .`:
```
cbsdk_static.lib(cbsdk.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in cbpy.obj
```
This is with VS2017, Qt5.11.2, Python 3.5 with pip 10.0.1 in a Miniconda environment. I don't have enough CMake nor pip experience to know how to fix this properly, but one of them needs to be changed so both runtimes are the same. Workaround for me was changing it in the vcxproj file and not run CMake again before installing with pip.

Sidenote: maybe the Python build instructions should say explicitly that right after running pip install one must leave the CereLink directory before trying import cerebus.cbpy in Python, otherwise it imports from the cerebus directory of this repo and error messages are confusing leading to frustration :P

**Comment by cboulay** [comment]
Hm... I'm amazed I've never run into this problem. I'll take a look as soon as I can.

> Sidenote: maybe the Python build instructions should say explicitly that right after running pip install one must leave the CereLink directory before trying import cerebus.cbpy in Python, otherwise it imports from the cerebus directory of this repo and error messages are confusing leading to frustration :P

This is true of any Python library and should be a good rule. If you ever want to debug a python library that you are working on and is under version control, then use `pip install -e .`, but yes, still change out of that directory. If we ever add instruction on how to use the Python package then I will try to be explicit about this.

**Comment by stinos** [comment]
> Hm... I'm amazed I've never run into this problem.

I assume something is different on my setup. Forgot to mention cmake version: 3.12.1

**Comment by cboulay** [comment]
As I tried to reproduce this on a fairly fresh Windows install, I ran into a different error because I had only Visual Studio 2017 installed and my particular configuration uses Python 3.5.4 which requires Visual Studio 2015. That made me realize that I've never actually tried this on VS 2017, I think I've only ever used 2015 for this project.

I'll try on a new conda env with Python 3.7 to see if I can get by with VS 2017. In case I don't have time to complete this fix today, and I don't answer back here in the next couple hours, you might want to stick to VS 2015 for now if you can.

**Comment by cboulay** [comment]
I have things working with MSVC 2017 and I still can't reproduce your error.

I used the Windows command found in the "try me first" part of the BUILD instructions [here](https://github.com/dashesy/CereLink/blob/master/BUILD.md#try-me-first) to build with MSVC2017.

I've updated the Wiki a bit [here](https://github.com/dashesy/CereLink/wiki/Install-Python-package#windows) but you can ignore the bits about Visual Studio 2015 because I used 2017 for the whole process and it still worked. I have VS 2015 installing in the background so there's a chance that it put some important files in place but I don't think that's the case.

`pip install .` failed to copy the Qt dll files (`Qt5Core.dll` and `Qt5Xml.dll`) in so I copied them manually from <repo>/dist to <path_to_python_env>/Lib/site-packages/cerebus.

After that everything worked.

I just finished getting CI working with another python library I work on (https://www.github.com/labstreaminglayer/liblsl-Python). Now that I'm familiar with how that works, I'll probably do the same for this project, and part of the output of that process will be building wheels that include all the dependencies that can then be installed with `pip install cerebus`.

Other details:
* `cmake version 3.12.18081601-MSVC_2`
* Be sure to delete your CereLink/build and CereLink/dist folders before any re-attempts. Qt-linked libraries have a nasty habit of keeping old configs and old objects around and using visual studio to clean the build dir is insufficient.
* MSVC2015 and 2017 are binary compatible so the Qt binaries for either should work, as long as they match the platform architecture (i.e. x64).

**Comment by stinos** [comment]
Thanks for checking on this. I dived into it and finally found the problem. First I noticed for some reason my pip version was 10.something instead of a later one. After upgrading, which also upgraded setuptools and distutils etc I could build cbpy: it turns out distutils is the one responsible for adding `/MT` or '/MD' to the compile command used by pip. And the newer version of distutils used /MD on my machine so all is fine. 

However, on another machine with a very very similar setup but a slight difference in VS2017 installation (and otherwise exactly same cmake, Qt, Python, distutils, ...) it does not work. In my opinion the logic in distutils is simply broken, for some reason it only wants to build with /MD if it finds the VC runtime redistributable dll in one specific directory (Microsoft.VC141.CRT) under the VS installation directory. That's bad, because those redistributable dlls aren't the ones used at runtime anyway and hence are far from related to whether using /MD is possible. It's also bad because this one machine doesn't have that particular directory since it hass Microsoft.VC150.CRT instead which is perfectly fine as far as VS goes. And it's also bad because that behaviour seems hardcoded and not really configurable so to get thinngs working you need to hack around: I ended up manually modifying _msvccompiler.py in the distutils module..

> pip install . failed to copy the Qt dll files (Qt5Core.dll and Qt5Xml.dll)

Same here, but at runtime it picks up the dll from the miniconda/bin directory so I didn't even make a copy. Also my pyd file only depend on Qt5Core.dll but not Qt5Xml.dll.

**Comment by dashesy** [comment]
> And it's also bad because that behaviour seems hardcoded and not really configurable so to get thinngs working you need to hack around: I ended up manually modifying _msvccompiler.py in the distutils module.

It means filing a bug with distutils is the best course of action, to have a fix at one point. I think distutils has not yet picked up the subtleties of VS2017 vc runtime
